### ISSUE TITLE
Lunchtime next week :) (13.-19.10.)

### ISSUE THREAD

**Issue by nanoparsec** [Postec14Lunchdate/Lunchtime#1]
Let's have lunch.

Location: 
Cocolo Ramen Bar
Paul-Lincke-Ufer 39
10999 Berlin
http://bit.ly/1pGBiPu

Day: Wednesday 15.10. ?

**Comment by eljojo** [comment]
Sounds perfect!
![AWESOME](http://smartbitchestrashybooks.com/images/uploads/AwesomeRennerGif.gif)

**Comment by thilo** [comment]
+1

**Comment by pxlpnk** [comment]
:dancers:

**Comment by madziaf** [comment]
Wed from 14, for me.
Tuesday im totally flexible
:)

**Comment by thilo** [comment]
so 2014-10-15 14:00:00 @ Cocolo it is?!

**Comment by pxlpnk** [comment]
I have to opt out. I forgot that I am not even in Berlin on this date.

The next time I am in again!

**Comment by bascht** [comment]
> so 2014-10-15 14:00:00 @ Cocolo it is?!

Still valid? :)

**Comment by nanoparsec** [comment]
Yep. Still valid.

**Comment by nanoparsec** [comment]
So, Wednesday 14:00 @Cocolo. Freue mich auf euch <3

**Comment by polarblau** [comment]
I will try to come as well — just a tad far away :smirk_cat: .

**Comment by nanoparsec** [comment]
Yay, we had a successful lunch <3 thanks for this awesome time.
