### ISSUE TITLE
Unexpected loss of persons

### ISSUE THREAD

**Issue by bascht** [Postec14Lunchdate/Lunchtime#3]
Version: 1.0
Platform: All

Status: NEW
Severity: Major
Priority: P1
### Reproduce steps:

1) Set up lunch date via Postec14Lunchdate
2) Wait 1 week
3) Check again
### Actual result:

![screenshot from 2014-10-13 12 40 09](https://cloud.githubusercontent.com/assets/51264/4612289/9c129dec-52c5-11e4-8197-e3adbfafe099.png)
### Expected result:

Lunch

**Comment by nanoparsec** [comment]
:) 
Laura hatte schon vorher gesagt, dass sie nicht kann.
Und das Tegelproblem ist leider auch schon lämger bekannt, kann aber nicht gefixt werden atm.
