### ISSUE TITLE
Next lunchtime - 28.10./29.10.

### ISSUE THREAD

**Issue by nanoparsec** [Postec14Lunchdate/Lunchtime#5]
When should we meet next?
Date: 28.10. or 29.10.?
Time: 12:30
Location: Ideas?

**Comment by eljojo** [comment]
12:30 sounds a bit too early, doesn't it?

**Comment by dajana** [comment]
agreed with the time. What about 1 pm here: http://www.yelp.de/biz/chan-asian-marketfood-berlin
(That's a Thai just a few steps away from Cocolo)

About the day: both would be fine

**Comment by skade** [comment]
I :+1:  @dajana s suggestion and opinion on times.

**Comment by thilo** [comment]
Have to skip this time. Sorry :(

**Comment by eljojo** [comment]
hi, i'll have to skip as well

**Comment by skade** [comment]
I still have that planned, anyone coming?

**Comment by bascht** [comment]
@nerdbabe Any update on this?
